// Copyright 2014 Iwan Aucamp
// vim: set ts=8 sw=8 noexpandtab filetype=asciidoc :
= link:https://github.com/aucampia/aucampia-gentoo-overlay[ Iwan Aucamp's Gentoo Overlay ]
Iwan Aucamp
2014-06-27
:toc:
:numbered:

== Info

repo_name:: +aucampia-gentoo-overlay+

git sources::
https::: link:https://github.com/aucampia/aucampia-gentoo-overlay.git[]
git::: link:git://github.com/aucampia/aucampia-gentoo-overlay.git[]
git+ssh::: link:git+ssh://github.com/aucampia/aucampia-gentoo-overlay.git[]

== News

2014-06-27::
	* Added +dev-java/maven-bin-3.2.2+

2014-06-14::
	* Added +app-cdr/isomd5sum-1.0.12+
	* Added +app-misc/liveusb-creator-3.11.8+

2014-06-13::
	* Added +dev-java/maven-bin-3.2.1+

== Instructions

NOTE: These commands require super user permissions (i.e. use +sudo+)

* Install layman
+
----
emerge --noreplace app-portage/layman
----

* List overlays
+
----
# without uri in layman.cfg
layman -o https://raw.githubusercontent.com/aucampia/aucampia-gentoo-overlay/master/aucampia-gentoo-overlay.xml -L

# with uri in layman.cfg
layman -L
----

* Add Overlay through layman
+
----
# without uri in layman.cfg
layman -o https://raw.githubusercontent.com/aucampia/aucampia-gentoo-overlay/master/aucampia-gentoo-overlay.xml -a aucampia-gentoo-overlay

# with uri in layman.cfg
layman -a aucampia-gentoo-overlay
----

* Update overlay
+
----
# without uri in layman.cfg
layman -o https://raw.githubusercontent.com/aucampia/aucampia-gentoo-overlay/master/aucampia-gentoo-overlay.xml -s aucampia-gentoo-overlay

# with uri in layman.cfg
layman -s aucampia-gentoo-overlay
----

* Permanently Add overlay to ++layman.cfg++:
+
WARNING: Use with care - might be unsafe
+
----
sed \
  -i.`date +%Y%m%d%H%M%S`.bak \
  '/^[[:blank:]]*overlays[[:blank:]]*:.*$/a\            https://raw.githubusercontent.com/aucampia/aucampia-gentoo-overlay/master/aucampia-gentoo-overlay.xml' /etc/layman/layman.cfg
----

* Permanently Add overlay to ++layman.cfg++ (manually):
** Open file in your editor
+
----
$EDITOR /etc/layman/layman.cfg
----

** Locate +overlays+ section:
+
----
...

overlays  : http://www.gentoo.org/proj/en/overlays/repositories.xml

...
----

** Add url to +overlays+ section:
+
----
diff -u /etc/layman/layman.cfg.20140613162703.bak /etc/layman/layman.cfg
--- /etc/layman/layman.cfg.20140613162703.bak	2014-06-13 16:26:58.563246255 +0200
+++ /etc/layman/layman.cfg	2014-06-13 16:27:03.073224185 +0200
@@ -38,6 +38,7 @@
 #            file:///var/lib/layman/my-list.xml
 
 overlays  : http://www.gentoo.org/proj/en/overlays/repositories.xml
+            https://raw.githubusercontent.com/aucampia/aucampia-gentoo-overlay/master/aucampia-gentoo-overlay.xml
 
 #-----------------------------------------------------------
 # The directory to scan for xml overlay definition files to include
----

== Credits

* +::gentoo+ -> +dev-java/maven-bin+
* +::sabayon+ -> +app-cdr/isomd5sum+
* +::bgo-overlay+ -> +app-misc/liveusb-creator+
* +::xarthisius+ -> +net-misc/gwibber+

== TODO

* Use versionator instead of bash variable expansion.
* Copy resources from other overlays with history [not needed now].
* File bug for gjl gjl_java_args
* File bug for uname in nexus ./bin/nexus
