= link:https://github.com/aucampia/aucampia-gentoo-overlay[Iwan Aucamp's Gentoo Overlay]

== Info

repo_name:: +aucampia-gentoo-overlay+

git sources::
https::: link:https://github.com/aucampia/aucampia-gentoo-overlay.git[]
git::: link:git://github.com/aucampia/aucampia-gentoo-overlay.git[]
git+ssh::: link:git+ssh://github.com/aucampia/aucampia-gentoo-overlay.git[]

== News

== Instructions

NOTE: These commands require super user permissions (i.e. use +sudo+)

* Install layman
+
----
emerge --noreplace app-portage/layman
----

* List overlays
+
----
# without uri in layman.cfg
layman -o https://raw.githubusercontent.com/aucampia/aucampia-gentoo-overlay/master/aucampia-gentoo-overlay.xml -L

# with uri in layman.cfg
layman -L
----

* Add Overlay through layman
+
----
# without uri in layman.cfg
layman -o https://raw.githubusercontent.com/aucampia/aucampia-gentoo-overlay/master/aucampia-gentoo-overlay.xml -a aucampia-gentoo-overlay

# with uri in layman.cfg
layman -a aucampia-gentoo-overlay
----

* Update overlay
+
----
# without uri in layman.cfg
layman -o https://raw.githubusercontent.com/aucampia/aucampia-gentoo-overlay/master/aucampia-gentoo-overlay.xml -s aucampia-gentoo-overlay

# with uri in layman.cfg
layman -s aucampia-gentoo-overlay
----

* Permanently Add overlay to ++layman.cfg++:
+
WARNING: Use with care - might be unsafe
+
----
sed \
  -i.`date +%Y%m%d%H%M%S`.bak \
  '/^[[:blank:]]*overlays[[:blank:]]*:.*$/a\            https://raw.githubusercontent.com/aucampia/aucampia-gentoo-overlay/master/aucampia-gentoo-overlay.xml' /etc/layman/layman.cfg
----

* Permanently Add overlay to ++layman.cfg++ (manually):
** Open file in your editor
+
----
$EDITOR /etc/layman/layman.cfg
----

** Locate +overlays+ section:
+
----
...

overlays  : http://www.gentoo.org/proj/en/overlays/repositories.xml

...
----

** Add url to +overlays+ section:
+
----
diff -u /etc/layman/layman.cfg.20140613162703.bak /etc/layman/layman.cfg
--- /etc/layman/layman.cfg.20140613162703.bak	2014-06-13 16:26:58.563246255 +0200
+++ /etc/layman/layman.cfg	2014-06-13 16:27:03.073224185 +0200
@@ -38,6 +38,7 @@
 #            file:///var/lib/layman/my-list.xml
 
 overlays  : http://www.gentoo.org/proj/en/overlays/repositories.xml
+            https://raw.githubusercontent.com/aucampia/aucampia-gentoo-overlay/master/aucampia-gentoo-overlay.xml
 
 #-----------------------------------------------------------
 # The directory to scan for xml overlay definition files to include
----

== Links

* link:http://devmanual.gentoo.org/[Gentoo Development Guide]
** link:http://devmanual.gentoo.org/quickstart/[Quickstart Ebuild Guide]
** link:http://devmanual.gentoo.org/general-concepts/index.html[General Concepts] / link:http://devmanual.gentoo.org/general-concepts/overlay/index.html[Overlay]
** link:http://devmanual.gentoo.org/ebuild-writing/index.html[Ebuild Writing] / link:http://devmanual.gentoo.org/ebuild-writing/variables/index.html[Variables]
* link:https://wiki.gentoo.org/wiki/Main_Page[Gentoo Wiki]
** link:https://wiki.gentoo.org/wiki/Overlay[Overlay]
** link:https://wiki.gentoo.org/wiki/Layman[Layman]
** link:https://wiki.gentoo.org/wiki/Repository_format[Repository format]
*** link:https://wiki.gentoo.org/wiki/Repository_format/metadata/layout.conf[metadata/layout.conf]
*** link:https://wiki.gentoo.org/wiki/Repository_format/profiles/repo_name[profiles/repo_name]
* link:https://www.gentoo.org/proj/en/overlays/[Gentoo Overlay Team]
** link:https://www.gentoo.org/proj/en/overlays/devguide.xml[Developers' Guide]
** link:https://www.gentoo.org/proj/en/overlays/userguide.xml[Users' Guide]
* link:http://sourceforge.net/projects/layman/[Layman @ SourceForge]
** link:http://layman.sourceforge.net/[Site]

=== Python

* link:http://wiki.gentoo.org/wiki/Project:Python[Gentoo Wiki / Python Project]
* link:http://www.gentoo.org/proj/en/Python/index.xml[gentoo.org / Python]

== Git Help

* link:http://git-scm.com/book[]
* link:http://git-scm.com/book/en/Distributed-Git-Contributing-to-a-Project#Commit-Guidelines[]

----
#git clone https://github.com/aucampia/gentoo-overlay.git
git clone https://github.com/aucampia/aucampia-gentoo-overlay.git
git add
git commit -a 
git push
git pull

## See origin details:
git remote show origin

## Change origin:
git remote set-url origin git@github.com:aucampia/aucampia-gentoo-overlay.git
git remote set-url origin https://github.com/aucampia/aucampia-gentoo-overlay.git
----

== Examples

* link:https://github.com/psomas/synnefo-overlay[Gentoo ebuild overlay for Synnefo]
* link:https://github.com/nutztherookie/wacfg-overlay[wacfg-overlay]

== Notes

----
wget http://www.gentoo.org/proj/en/overlays/repositories.xml
wget http://gpo.zugaina.org/lst/gpo-repositories.xml
sed -n 's/^.*<source[^>]\+>.*\(github.com\/.*\).git<\/source>.*$/\1/gp' repositories.xml | sort | uniq
----

----
ebuild ... manifest
sudo ebuild ... clean package
----

* link:http://dev.gentoo.org/~zmedico/portage/doc/man/portage.5.html[]
* /usr/portage/metadata/dtd/repositories.dtd

