// Copyright 2014 Iwan Aucamp
// vim: set ts=8 sw=8 :
// vim: set filetype=asciidoc :
= link:https://github.com/aucampia/aucampia-gentoo-overlay[ Iwan Aucamp's Gentoo Overlay ]
Iwan Aucamp
2014-06-27
:toc:
:numbered:

== Info

repo_name:: +aucampia-gentoo-overlay+

git sources::
https::: link:https://github.com/aucampia/aucampia-gentoo-overlay.git[]
git::: link:git://github.com/aucampia/aucampia-gentoo-overlay.git[]
git+ssh::: link:git+ssh://github.com/aucampia/aucampia-gentoo-overlay.git[]

== News

2014-06-27::
	* Added +dev-java/maven-bin-3.2.2+

2014-06-14::
	* Added +app-cdr/isomd5sum-1.0.12+
	* Added +app-misc/liveusb-creator-3.11.8+

2014-06-13::
	* Added +dev-java/maven-bin-3.2.1+

== Instructions

NOTE: These commands require super user permissions (i.e. use +sudo+)

* Install layman
+
----
emerge --noreplace app-portage/layman
----

* List overlays
+
----
# without uri in layman.cfg
layman -o https://raw.githubusercontent.com/aucampia/aucampia-gentoo-overlay/master/aucampia-gentoo-overlay.xml -L

# with uri in layman.cfg
layman -L
----

* Add Overlay through layman
+
----
# without uri in layman.cfg
layman -o https://raw.githubusercontent.com/aucampia/aucampia-gentoo-overlay/master/aucampia-gentoo-overlay.xml -a aucampia-gentoo-overlay

# with uri in layman.cfg
layman -a aucampia-gentoo-overlay
----

* Update overlay
+
----
# without uri in layman.cfg
layman -o https://raw.githubusercontent.com/aucampia/aucampia-gentoo-overlay/master/aucampia-gentoo-overlay.xml -s aucampia-gentoo-overlay

# with uri in layman.cfg
layman -s aucampia-gentoo-overlay
----

* Permanently Add overlay to ++layman.cfg++:
+
WARNING: Use with care - might be unsafe
+
----
sed \
  -i.`date +%Y%m%d%H%M%S`.bak \
  '/^[[:blank:]]*overlays[[:blank:]]*:.*$/a\            https://raw.githubusercontent.com/aucampia/aucampia-gentoo-overlay/master/aucampia-gentoo-overlay.xml' /etc/layman/layman.cfg
----

* Permanently Add overlay to ++layman.cfg++ (manually):
** Open file in your editor
+
----
$EDITOR /etc/layman/layman.cfg
----

** Locate +overlays+ section:
+
----
...

overlays  : http://www.gentoo.org/proj/en/overlays/repositories.xml

...
----

** Add url to +overlays+ section:
+
----
diff -u /etc/layman/layman.cfg.20140613162703.bak /etc/layman/layman.cfg
--- /etc/layman/layman.cfg.20140613162703.bak	2014-06-13 16:26:58.563246255 +0200
+++ /etc/layman/layman.cfg	2014-06-13 16:27:03.073224185 +0200
@@ -38,6 +38,7 @@
 #            file:///var/lib/layman/my-list.xml
 
 overlays  : http://www.gentoo.org/proj/en/overlays/repositories.xml
+            https://raw.githubusercontent.com/aucampia/aucampia-gentoo-overlay/master/aucampia-gentoo-overlay.xml
 
 #-----------------------------------------------------------
 # The directory to scan for xml overlay definition files to include
----

== Links

* link:http://devmanual.gentoo.org/[ Gentoo Development Guide ]
** link:http://devmanual.gentoo.org/quickstart/[ Quickstart Ebuild Guide ]
** link:http://devmanual.gentoo.org/general-concepts/index.html[ General Concepts ]
*** link:http://devmanual.gentoo.org/general-concepts/filesystem/index.html[ Filesystem ]
*** link:http://devmanual.gentoo.org/general-concepts/overlay/index.html[ Overlay ]
*** link:http://devmanual.gentoo.org/general-concepts/use-flags/index.html[ USE Flags ]
** link:http://devmanual.gentoo.org/ebuild-writing/index.html[ Ebuild Writing ]
*** link:http://devmanual.gentoo.org/ebuild-writing/eapi/index.html[ EAPI Usage and Description ]
*** link:http://devmanual.gentoo.org/ebuild-writing/users-and-groups/index.html[ Users and Groups ]
*** link:http://devmanual.gentoo.org/ebuild-writing/variables/index.html[ Variables ]
*** link:http://devmanual.gentoo.org/ebuild-writing/misc-files/index.html[ Miscellaneous Files ]
**** link:http://devmanual.gentoo.org/ebuild-writing/misc-files/metadata/index.html[ Package and Category +metadata.xml+ ]
**** link:http://devmanual.gentoo.org/ebuild-writing/misc-files/changelog/index.html[ ChangeLog ]
**** link:http://devmanual.gentoo.org/ebuild-writing/misc-files/patches/index.html[ Patches ]
** link:https://devmanual.gentoo.org/eclass-reference/index.html[ Eclass Reference ]
*** link:https://devmanual.gentoo.org/eclass-reference/versionator.eclass/index.html[ +VERSIONATOR+ ]
**** link:file:///usr/portage/eclass/versionator.eclass[]
*** link:https://devmanual.gentoo.org/eclass-reference/vala.eclass/index.html[ +VALA+ ]
**** link:file:///usr/portage/eclass/vala.eclass[]
*** link:https://devmanual.gentoo.org/eclass-reference/git-r3.eclass/index.html[ +GIT-R3+ ]
**** link:file:///usr/portage/eclass/git-r3.eclass[]
*** link:https://devmanual.gentoo.org/eclass-reference/eutils.eclass/index.html[ +EUTILS+ ]
**** link:file:///usr/portage/eclass/eutils.eclass[]
** link:http://devmanual.gentoo.org/tools-reference/index.html[ Tools Reference ]
*** link:http://devmanual.gentoo.org/tools-reference/echangelog/index.html[ echangelog -- ChangeLog Generation ]
*** link:http://devmanual.gentoo.org/tools-reference/ekeyword/index.html[ ekeyword -- Keywording ]
* link:https://wiki.gentoo.org/wiki/Main_Page[ Gentoo Wiki ]
** link:https://wiki.gentoo.org/wiki/Overlay[ Overlay ]
** link:https://wiki.gentoo.org/wiki/Layman[ Layman ]
** link:https://wiki.gentoo.org/wiki/Repository_format[ Repository format ]
*** link:https://wiki.gentoo.org/wiki/Repository_format/metadata/layout.conf[ +metadata/layout.conf+ ]
*** link:https://wiki.gentoo.org/wiki/Repository_format/profiles/repo_name[ +profiles/repo_name+ ]
* link:http://www.gentoo.org/proj/en/devrel/handbook/handbook.xml?full=1[ Gentoo Developer Handbook ]
* link:https://www.gentoo.org/proj/en/overlays/[ Gentoo Overlay Team ]
** link:https://www.gentoo.org/proj/en/overlays/devguide.xml[ Developers' Guide ]
** link:https://www.gentoo.org/proj/en/overlays/userguide.xml[ Users' Guide ]
* link:http://sourceforge.net/projects/layman/[ Layman @ SourceForge ]
** link:http://layman.sourceforge.net/[ Site ]

=== Python

* link:http://wiki.gentoo.org/wiki/Project:Python[ Gentoo Wiki / Python Project ]
* link:http://www.gentoo.org/proj/en/Python/index.xml[ gentoo.org / Python ]
** link:http://wiki.gentoo.org/wiki/Project:Python/python-r1[ python-r1 (Developer's Guide) ]
** link:http://wiki.gentoo.org/wiki/Python-r1/examples[ python-r1 / examples ]
** link:http://devmanual.gentoo.org/[ Gentoo Development Guide ] / link:https://devmanual.gentoo.org/eclass-reference/index.html[ Eclass Reference ]
*** link:https://devmanual.gentoo.org/eclass-reference/python-r1.eclass/index.html[ +PYTHON-R1+ ]
**** link:file:///usr/portage/eclass/python-r1.eclass[]
*** link:https://devmanual.gentoo.org/eclass-reference/distutils-r1.eclass/index.html[ +DISTUTILS-R1+ ]
**** link:file:///usr/portage/eclass/distutils-r1.eclass[]

=== Java

* link:http://www.gentoo.org/proj/en/java/[ gentoo.org / The Java Project ]
** link:http://www.gentoo.org/proj/en/java/java-devel.xml[ Gentoo Java Packaging Guide ]
** link:http://devmanual.gentoo.org/[ Gentoo Development Guide ] / link:https://devmanual.gentoo.org/eclass-reference/index.html[ Eclass Reference ] / link:https://devmanual.gentoo.org/eclass-reference/java-pkg-2.eclass/index.html[ +JAVA-PKG-2+ ]
**** link:file:///usr/portage/eclass/java-pkg-2.eclass[]

=== GNU Autotools

==== GNU Autoconf

* link:http://www.gnu.org/software/autoconf/manual/[ Manual ]
** link:http://www.gnu.org/software/autoconf/manual/autoconf.html[ HTML single page ]
** link:http://www.gnu.org/software/autoconf/manual/html_node/index.html[ HTML multi page ]
** link:http://www.gnu.org/software/autoconf/manual/autoconf.pdf[ PDF ]

=== GNU Make

* link:http://www.gnu.org/software/make/manual/[ Manual ]
** link:http://www.gnu.org/software/make/manual/make.html[ HTML single page ]
** link:http://www.gnu.org/software/make/manual/html_node/index.html[ HTML multi page ]
** link:http://www.gnu.org/software/make/manual/make.pdf[ PDF ]

=== GNU Make Standard Library

* link:http://gmsl.sourceforge.net/[ Website ]
* link:http://sourceforge.net/projects/gmsl/[ SourceForge Project Page ]
** link:http://gmsl.cvs.sourceforge.net/viewvc/gmsl/[ ViewVC ]


== Git Help

* link:http://git-scm.com/book[]
* link:http://git-scm.com/book/en/Distributed-Git-Contributing-to-a-Project#Commit-Guidelines[]

----
#git clone https://github.com/aucampia/gentoo-overlay.git
git clone https://github.com/aucampia/aucampia-gentoo-overlay.git
git add
git commit -a 
git push
git pull

## See origin details:
git remote show origin

## Change origin:
git remote set-url origin git@github.com:aucampia/aucampia-gentoo-overlay.git
git remote set-url origin https://github.com/aucampia/aucampia-gentoo-overlay.git
----

== Examples

* link:https://github.com/psomas/synnefo-overlay[ +synnefo+ ]
* link:https://github.com/nutztherookie/wacfg-overlay[ +wacfg+ ]
* link:https://github.com/shiznix/unity-gentoo[ +unity-gentoo+ ]
* link:https://github.com/ercpe/lh-overlay[ +last-hope+ ]
* link:https://github.com/sebasmagri/portage[ +sebasmagri+ ]

== Credits

* +::gentoo+ -> +dev-java/maven-bin+
* +::sabayon+ -> +app-cdr/isomd5sum+
* +::bgo-overlay+ -> +app-misc/liveusb-creator+
* +::xarthisius+ -> +net-misc/gwibber+

////
* +::unity-gentoo+ -> +dev-libs/libaccounts-glib+
* +::unity-gentoo+ -> +dev-libs/libsignon-glib+
////

== TODO

* Use versionator instead of bash variable expansion.
* Copy resources from other overlays with history [not needed now].
* File bug for gjl gjl_java_args
* File bug for uname in nexus ./bin/nexus

== Notes

----
wget http://www.gentoo.org/proj/en/overlays/repositories.xml
wget http://gpo.zugaina.org/lst/gpo-repositories.xml
sed -n 's/^.*<source[^>]\+>.*\(github.com\/.*\).git<\/source>.*$/\1/gp' repositories.xml | sort | uniq
----

----
find . \( -name tmp -o -name .git \) -prune -o -name '*.ebuild' -type f -print
----

----
find . \( -name tmp -o -name upstream -o -name .git \) -prune -o -name '*.patch' -type f -print
find . \( -name tmp -o -name upstream -o -name .git \) -prune -o -name 'metadata.xml' -type f -print
find . \( -name tmp -o -name upstream -o -name .git \) -prune -o -name '*.ebuild' -type f -print
find . \( -name tmp -o -name upstream -o -name .git \) -prune -o -name '*.asciidoc' -type f -print
grep -r --include='*.ebuild' --exclude-dir=tmp --exclude-dir=upstream --exclude-dir=.git --exclude-dir=distfiles inherit .
----

----
find /usr/portage/ \( -name tmp -o -name .git -o -name distfiles \) -prune -o -name '*.ebuild' -type f -print
find /usr/portage/ \( -name tmp -o -name .git -o -name distfiles \) -prune -o -name '*-bin*.ebuild' -type f -print | xargs grep 'inherit.*java'
grep -r --include='*.ebuild' --exclude-dir=.git --exclude-dir=distfiles get_version_component_range /usr/portage/
grep -r --include='*.ebuild' --exclude-dir=.git --exclude-dir=distfiles PATCHES /usr/portage/
grep -r --include='*.ebuild' --exclude-dir=.git --exclude-dir=distfiles gecko /usr/portage/
grep -r --include='*.ebuild' --exclude-dir=.git --exclude-dir=distfiles fowners /usr/portage/
grep -r --include='*.ebuild' --exclude-dir=.git --exclude-dir=distfiles java-pkg_newjar /usr/portage/
grep -r --include='*.ebuild' --exclude-dir=.git --exclude-dir=distfiles extglob /usr/portage/
----

----
find /usr/portage/ \( -name tmp -o -name .git -o -name distfiles \) -prune -o -name '*.eclass' -type f -print
find /usr/portage/ \( -name tmp -o -name .git -o -name distfiles \) -prune -o -name '*.eclass' -type f -print
grep -ri /usr/portage/
----

----
ls -ld /usr/portage/*/*/files/*.patch
ls -d /usr/portage/*/*/files/*.patch | sed 's,[^/]\+\/[^/]\+$,,g' | sort | uniq
----

----
eix --in-overlay aucampia-gentoo-overlay
----

----
find . \( -name tmp -o -name upstream -o -name .git \) -prune -o -name '*.ebuild' -type f -printf '%h\n' | sort | uniq
find . \( -name tmp -o -name upstream -o -name .git \) -prune -o -name 'ChangeLog' -type f -print | sort
ECHANGELOG_USER="Iwan Aucamp <aucampia@gmail.com>" echangelog "..."
find . \( -name tmp -o -name upstream -o -name .git \) -prune -o -name 'metadata.xml' -type f -print | xargs -I {} xmllint --valid {} > /dev/null
find . \( -name tmp -o -name upstream -o -name .git \) -prune -o -name '*.ebuild' -type f -print | xargs -I{} ebuild {} manifest
sed -i '/^MISC README/d' */*/Manifest
repoman -p -d full
----

----
/usr/portage/packages/
/usr/portage/licenses/
grep changelog /usr/portage/*/*/metadata.xml
xmllint --valid metadata.xml
grep -e qt4 -e gtk /usr/portage/profiles/use.desc
view /usr/portage/profiles/arch.list
egrep 'flag.*(gtk|qt4)' /usr/portage/*/*/metadata.xml


git log | grep Auth | sort | uniq | sed 's,Author: \([^<]\+\) <\([^>]\+\)>,\t\t<maintainer status="unknown">\n\t\t\t<email>\2</email>\n\t\t\t<name>\1</name>\n\t\t</maintainer>,g'
----

----
ekeyword ~amd64 ~x86 libturpial-1.0.ebuild

repoman -p

ebuild ... manifest
sudo ebuild ... clean package
----

----

ls -d /usr/portage/*java*/*bin*/*.ebuild

fowners

permissions is not changed on ebuild ... merge
----

----
app-portage/gentoolkit-dev
app-portage/overlay-utils
www-client/pybugz
app-doc/devmanual
----

----
http://git.overlays.gentoo.org/gitweb/?p=proj/java-config.git;a=summary
man 8 runscript
http://www.gentoo.org/doc/en/handbook/handbook-x86.xml?part=2&chap=4#doc_chap4
http://git.overlays.gentoo.org/gitweb/?p=proj/java-config.git;a=blob;f=src/launcher.bash;h=3d777571ded8b561b8f6a42467ed2fad41b6cdad;hb=HEAD
----

* link:http://dev.gentoo.org/~zmedico/portage/doc/man/portage.5.html[]
* link:file:///usr/portage/metadata/dtd/repositories.dtd[]
* link:file:///usr/portage/metadata/dtd/metadata.dtd[]
* link:file:///usr/portage/profiles/license_groups[]
* link:file:///usr/portage/profiles/arch.list[]
* link:file:////usr/portage/profiles/use.desc[]

